# =============================================================================
# File      : 05_taxonomy.R
# Project   : MetaBarFlow – generalised metabarcoding pipeline
# Author    : David Singer
# Date      : 2026-03-03
# Description: Taxonomic assignment for ASVs generated by 04_DADA2_ASV.R.
#              Two complementary approaches:
#                1. VSEARCH blast6 → Pct_identity + GenBank
#                2. DADA2 assignTaxonomy → taxonomy levels + bootstrap scores
#              Marker-aware: handles PR2 (18S), UNITE (ITS), SILVA (16S).
#              Outputs:
#                - [MARKER]_ASS.csv : unified 23-column assignment matrix
#              Updates read_tracking.tsv.
# Usage     : Rscript 05_taxonomy.R pipeline_18S/config.R
# =============================================================================

suppressPackageStartupMessages({
    library(dada2)
})

# =============================================================================
# UTILITIES
# =============================================================================

log_r <- function(...) {
    cat(paste0(..., "\n"))
}

write_fasta <- function(sequences, names, file) {
    con <- file(file, open = "w")
    for (i in seq_along(sequences)) {
        writeLines(paste0(">", names[i]), con)
        writeLines(sequences[i], con)
    }
    close(con)
}

update_read_tracking <- function(tracking_file, new_data) {
    if (file.exists(tracking_file)) {
        # Read first column as character to preserve leading zeros (e.g. "033")
        # row.names=1 silently converts "033" -> 33 -> "33", causing duplicate
        # rows and, on re-runs, ragged columns. Mirrors 04_DADA2_ASV.R.
        raw <- read.table(tracking_file,
                          header      = TRUE,
                          sep         = "\t",
                          check.names = FALSE,
                          colClasses  = "character",
                          row.names   = NULL)
        existing <- raw[, -1, drop = FALSE]
        rownames(existing) <- raw[, 1]
        for (col in colnames(new_data)) {
            existing[rownames(new_data), col] <- new_data[, col]
        }
        write.table(existing, tracking_file,
                    sep       = "\t",
                    quote     = FALSE,
                    col.names = NA)
    } else {
        write.table(new_data, tracking_file,
                    sep       = "\t",
                    quote     = FALSE,
                    col.names = NA)
    }
}

# --- Marker-specific GenBank accession extraction ----------------------------

#' PR2 mothur: AB353770.1.1740_U -> AB353770.1
extract_genbank_pr2 <- function(hit) {
    if (is.na(hit)) return(NA_character_)
    hit <- gsub("^>", "", hit)
    gsub("\\.[0-9]+_[A-Z]+$", "", hit)
}

#' SILVA: AY846379.1.1791 -> AY846379.1
extract_genbank_silva <- function(hit) {
    if (is.na(hit)) return(NA_character_)
    hit <- gsub("^>", "", hit)
    gsub("\\.[0-9]+$", "", hit)
}

#' UNITE: UDB016649|k__Fungi;...|SH1281904.10FU -> SH1281904.10FU
extract_genbank_unite <- function(hit) {
    if (is.na(hit)) return(NA_character_)
    hit <- gsub("^>", "", hit)
    parts <- strsplit(hit, "\\|")[[1]]
    if (length(parts) >= 3) parts[3] else NA_character_
}

#' Dispatch GenBank extraction by marker
extract_genbank <- function(hit, marker) {
    switch(marker,
        "18S" = extract_genbank_pr2(hit),
        "ITS" = extract_genbank_unite(hit),
        "16S" = extract_genbank_silva(hit),
        stop("Unknown marker: ", marker)
    )
}

# =============================================================================
# INITIALISATION
# =============================================================================

args <- commandArgs(trailingOnly = TRUE)
if (length(args) < 1) {
    stop("Usage: Rscript 05_taxonomy.R <path/to/config.R>")
}
config_path <- normalizePath(args[1], mustWork = TRUE)
source(config_path)

log_file <- file.path(LOG_DIR, "05_taxonomy.log")
dir.create(LOG_DIR,   recursive = TRUE, showWarnings = FALSE)
dir.create(STEP5_DIR, recursive = TRUE, showWarnings = FALSE)

sink(file = log_file, append = FALSE, split = TRUE)

log_r("=============================================================================")
log_r("  05_taxonomy.R started : ", format(Sys.time(), "%Y-%m-%d %H:%M:%S"))
log_r("=============================================================================")
log_r("  Marker       : ", MARKER)
log_r("  Config       : ", config_path)
log_r("  Input RDS    : ", OUT_SEQTAB_RDS)
log_r("  Output       : ", STEP5_DIR)
log_r("  Threads      : ", THREADS)
log_r("-----------------------------------------------------------------------------")

# =============================================================================
# STEP 1 — LOAD SEQTAB AND SEQUENCES
# =============================================================================

log_r("----- Step 1: Load seqtab : ", format(Sys.time(), "%H:%M:%S"), " -----")

if (!file.exists(OUT_SEQTAB_RDS)) {
    stop("seqtab_nochim.rds not found at ", OUT_SEQTAB_RDS,
         " -- run 04_DADA2_ASV.R first.")
}

seqtab   <- readRDS(OUT_SEQTAB_RDS)
asv_ids  <- colnames(seqtab)
nb_reads <- colSums(seqtab)

# Recover sequences from FASTA — colnames of seqtab are ASV IDs after step 04
if (!file.exists(OUT_FASTA)) {
    stop("FASTA file not found at ", OUT_FASTA, " -- run 04_DADA2_ASV.R first.")
}

fasta_lines   <- readLines(OUT_FASTA)
header_idx    <- grep("^>", fasta_lines)
sequences     <- fasta_lines[header_idx + 1]
asv_ids_fasta <- gsub("^>", "", fasta_lines[header_idx])

if (!identical(asv_ids, asv_ids_fasta)) {
    stop("ASV ID mismatch between seqtab_nochim.rds and FASTA file.")
}

n_asvs <- length(asv_ids)
log_r("  ASVs loaded : ", n_asvs)
log_r("  Samples     : ", nrow(seqtab))

# =============================================================================
# STEP 2 — VSEARCH BLAST6
# =============================================================================

log_r("----- Step 2: VSEARCH blast6 : ", format(Sys.time(), "%H:%M:%S"), " -----")

# Select database based on marker
DB_VSEARCH <- switch(MARKER,
    "18S" = DB_PR2_VSEARCH,
    "ITS" = DB_UNITE_VSEARCH,
    "16S" = DB_SILVA_VSEARCH,
    stop("Unknown marker: ", MARKER)
)

log_r("  Database    : ", DB_VSEARCH)
log_r("  Identity    : ", VSEARCH_ID)
log_r("  maxaccepts  : ", VSEARCH_MAXACCEPTS)
log_r("  maxrejects  : ", VSEARCH_MAXREJECTS)
log_r("  Threads     : ", VSEARCH_THREADS)

# Write temporary FASTA for VSEARCH
vsearch_input <- file.path(STEP5_DIR, paste0(MARKER, "_vsearch_input.fasta"))
write_fasta(sequences, asv_ids, vsearch_input)

vsearch_cmd <- paste(
    VSEARCH_PATH,
    "--usearch_global", vsearch_input,
    "--db",             DB_VSEARCH,
    "--id",             VSEARCH_ID,
    "--blast6out",      OUT_VSEARCH_BLAST6,
    "--output_no_hits",
    "--maxaccepts",     VSEARCH_MAXACCEPTS,
    "--maxrejects",     VSEARCH_MAXREJECTS,
    "--threads",        VSEARCH_THREADS
)

log_r("  Running VSEARCH...")
ret <- system(vsearch_cmd)
if (ret != 0) stop("VSEARCH failed with exit code ", ret)
log_r("  VSEARCH complete.")

# Parse blast6 output
blast6 <- read.table(OUT_VSEARCH_BLAST6,
                     sep              = "\t",
                     header           = FALSE,
                     quote            = "",
                     stringsAsFactors = FALSE,
                     col.names        = c("query", "target", "pct_id",
                                          "alnlen", "mismatches", "gaps",
                                          "qstart", "qend", "tstart",
                                          "tend", "evalue", "bitscore"))

blast6[blast6 == "*"] <- NA

# Extract GenBank accession — marker-specific
blast6$GenBank <- sapply(blast6$target, extract_genbank, marker = MARKER)

# Reorder to match asv_ids
blast6 <- blast6[match(asv_ids, blast6$query), ]
rownames(blast6) <- asv_ids

n_assigned_vsearch <- sum(!is.na(blast6$GenBank))
log_r("  ASVs with VSEARCH hit : ", n_assigned_vsearch, " / ", n_asvs,
      " (", round(n_assigned_vsearch / n_asvs * 100, 1), "%)")

file.remove(vsearch_input)

# =============================================================================
# STEP 3 — ASSIGN TAXONOMY (DADA2)
# =============================================================================

log_r("----- Step 3: assignTaxonomy : ", format(Sys.time(), "%H:%M:%S"), " -----")

# Select database based on marker
DB_DADA2 <- switch(MARKER,
    "18S" = DB_PR2_DADA2,
    "ITS" = DB_UNITE_DADA2,
    "16S" = DB_SILVA_DADA2,
    stop("Unknown marker: ", MARKER)
)

log_r("  Database    : ", DB_DADA2)
log_r("  Threads     : ", THREADS)

taxa_boot <- assignTaxonomy(
    seqs             = sequences,
    refFasta         = DB_DADA2,
    multithread      = THREADS,
    outputBootstraps = TRUE,
    verbose          = TRUE
)

taxa_raw <- taxa_boot$tax
boot_raw <- taxa_boot$boot

# =============================================================================
# STEP 4 — MARKER-SPECIFIC TAXONOMY MAPPING
# =============================================================================

log_r("----- Step 4: Taxonomy mapping : ", format(Sys.time(), "%H:%M:%S"), " -----")

# Initialise empty 9-level matrices
taxa <- matrix(NA,
               nrow     = nrow(taxa_raw),
               ncol     = length(TAXO_LEVELS),
               dimnames = list(rownames(taxa_raw), TAXO_LEVELS))
boot <- matrix(NA,
               nrow     = nrow(boot_raw),
               ncol     = length(TAXO_LEVELS),
               dimnames = list(rownames(boot_raw), TAXO_LEVELS))

if (MARKER == "18S") {
    # PR2 v5.1.0 — 9 native levels — direct mapping
    if (ncol(taxa_raw) == length(TAXO_LEVELS)) {
        taxa[] <- taxa_raw
        boot[] <- boot_raw
    } else {
        log_r("  WARNING: PR2 returned ", ncol(taxa_raw), " columns — expected ",
              length(TAXO_LEVELS), " — padding with NA.")
        n <- min(ncol(taxa_raw), length(TAXO_LEVELS))
        taxa[, 1:n] <- taxa_raw[, 1:n]
        boot[, 1:n] <- boot_raw[, 1:n]
    }

} else if (MARKER == "ITS") {
    # UNITE — 7 levels (k,p,c,o,f,g,s) mapped to 9-level standard
    # Domain=Eukaryota, Supergroup=Obazoa hardcoded (only k__Fungi in database)
    # Division <- Phylum (p__), Subdivision=NA
    # Strip prefixes (k__, p__, c__, o__, f__, g__, s__)
    unite_map <- c(
        "Division"   = 2,   # Phylum -> Division
        "Class"      = 3,
        "Order"      = 4,
        "Family"     = 5,
        "Genus"      = 6,
        "Species"    = 7
    )
    taxa[, "Domain"]     <- "Eukaryota"
    taxa[, "Supergroup"] <- "Obazoa"
    boot[, "Domain"]     <- 100
    boot[, "Supergroup"] <- 100

    for (lev in names(unite_map)) {
        col_idx <- unite_map[lev]
        if (col_idx <= ncol(taxa_raw)) {
            vals <- taxa_raw[, col_idx]
            # Strip UNITE prefixes e.g. k__, p__, c__
            vals <- gsub("^[a-z]__", "", vals)
            taxa[, lev] <- vals
            boot[, lev] <- boot_raw[, col_idx]
        }
    }
    # Subdivision remains NA — not present in UNITE

} else if (MARKER == "16S") {
    # SILVA 138.2 — 6 levels (Domain, Phylum, Class, Order, Family, Genus)
    # mapped to 9-level standard
    # Division, Subdivision, Species remain NA
    silva_map <- c(
        "Domain"     = 1,
        "Supergroup" = 2,   # Phylum -> Supergroup
        "Class"      = 3,
        "Order"      = 4,
        "Family"     = 5,
        "Genus"      = 6
    )
    for (lev in names(silva_map)) {
        col_idx <- silva_map[lev]
        if (col_idx <= ncol(taxa_raw)) {
            taxa[, lev] <- taxa_raw[, col_idx]
            boot[, lev] <- boot_raw[, col_idx]
        }
    }
    # Division, Subdivision, Species remain NA
}

rownames(taxa) <- asv_ids
rownames(boot) <- asv_ids

n_assigned_dada2 <- sum(rowSums(!is.na(taxa)) > 0)
log_r("  ASVs with assignTaxonomy hit : ", n_assigned_dada2, " / ", n_asvs,
      " (", round(n_assigned_dada2 / n_asvs * 100, 1), "%)")

# =============================================================================
# STEP 5 — BUILD ASS MATRIX
# =============================================================================

log_r("----- Step 5: Build ASS matrix : ", format(Sys.time(), "%H:%M:%S"), " -----")

boot_cols <- paste0(TAXO_LEVELS, "_boot")

ass <- data.frame(
    ASV_ID       = asv_ids,
    Nb_reads     = as.integer(nb_reads[asv_ids]),
    Pct_identity = as.numeric(blast6[asv_ids, "pct_id"]),
    GenBank      = blast6[asv_ids, "GenBank"],
    stringsAsFactors = FALSE
)

# Taxonomy columns
for (lev in TAXO_LEVELS) {
    ass[[lev]] <- taxa[asv_ids, lev]
}

# Bootstrap columns — convert to 0-1 scale
for (i in seq_along(TAXO_LEVELS)) {
    ass[[boot_cols[i]]] <- as.numeric(boot[asv_ids, TAXO_LEVELS[i]]) / 100
}

# Sequence
ass$Sequence <- sequences

log_r("  ASS matrix built : ", nrow(ass), " rows x ", ncol(ass), " columns")

# =============================================================================
# STEP 6 — WRITE ASS
# =============================================================================

log_r("----- Step 6: Write ASS : ", format(Sys.time(), "%H:%M:%S"), " -----")

write.table(ass,
            file      = OUT_ASS,
            sep       = ";",
            quote     = FALSE,
            row.names = FALSE)

log_r("  ASS written : ", OUT_ASS)

# =============================================================================
# STEP 7 — UPDATE READ TRACKING
# =============================================================================

log_r("----- Step 7: Update read tracking : ", format(Sys.time(), "%H:%M:%S"), " -----")

assigned_asvs <- asv_ids[rowSums(!is.na(taxa)) > 0]
track_tax <- data.frame(
    step05_assigned = rowSums(seqtab[, assigned_asvs, drop = FALSE]),
    row.names       = rownames(seqtab)
)
update_read_tracking(READ_TRACKING, track_tax)
log_r("  Read tracking updated.")

# =============================================================================
# FOOTER
# =============================================================================

log_r("=============================================================================")
log_r("  05_taxonomy.R finished : ", format(Sys.time(), "%Y-%m-%d %H:%M:%S"))
log_r("  Log    : ", log_file)
log_r("  ASS    : ", OUT_ASS)
log_r("  BLAST6 : ", OUT_VSEARCH_BLAST6)
log_r("=============================================================================")

sink()
